# Vivado constraints for the packaged can_top IP.
#
# Apply this file at the block-design/top-level project. The block design
# should provide the 100 MHz APB clock and the Clocking Wizard should provide
# can_clk. Do not create a second clock on either net if Vivado already has a
# clock propagated from the PS or Clocking Wizard.

# Block-design clock relationship
#
# The reported clock names are generated at the BD/top level, not at the
# can_top IP boundary. clk_fpga_0 is the 100 MHz source feeding the Clocking
# Wizard. Define it as a primary clock only when the BD does not already have
# a clock constraint for it. The Clocking Wizard IP XDC should define
# clk_out1_can_bd_clk_wiz_0_0 as a generated clock from this source.
set fpga_clock_source [get_ports -quiet clk_fpga_0]
if {![llength $fpga_clock_source]} {
    set fpga_clock_source [get_pins -quiet -hier -regexp {.*\/(FCLK_CLK0|clk_fpga_0)$}]
}
if {[llength $fpga_clock_source] &&
    [llength [get_clocks -quiet clk_fpga_0]] == 0} {
    create_clock -name clk_fpga_0 -period 10.000 \
        -waveform {0.000 5.000} $fpga_clock_source
}

# Do not create primary clocks on s_apb_pclk or can_clk here. In the BD they
# are internal clock nets, and can_clk must remain a generated clock from the
# Clocking Wizard rather than becoming a new unrelated primary clock.

# The CAN RX pin is an asynchronous physical input. This constraint prevents
# a nonexistent external launch clock from producing misleading input timing
# violations. The RTL should still synchronize this signal before using it in
# clocked CAN logic; this constraint is not a metastability fix.
if {[llength [get_ports -quiet can_rx]]} {
    set_false_path -from [get_ports can_rx]
}

# Mark all two-flop synchronizer stages in this IP. ASYNC_REG is also present
# in the RTL, but setting it here covers packaged/netlist flows.
set can_sync_cells [get_cells -quiet -hier -regexp {.*u_can_ch0/.*/(S1|S2|S1_reg|S2_reg|dst_sync1|dst_sync2|dst_sync1_reg|dst_sync2_reg)$}]
if {[llength $can_sync_cells]} {
    set_property ASYNC_REG TRUE $can_sync_cells
}

# Do not time the asynchronous source into the first destination flop. The
# second flop remains timed, so the synchronizer still has a real MTBF window.
set level_sync_first_pins [get_pins -quiet -hier -regexp {.*u_can_ch0/.*/(S1|S1_reg)/D$}]
if {[llength $level_sync_first_pins]} {
    set_false_path -to $level_sync_first_pins
}
set pulse_sync_first_pins [get_pins -quiet -hier -regexp {.*u_can_ch0/(tx_ok_sync|tx_err_sync|arblst_sync|rx_ok_sync)/(dst_sync1|dst_sync1_reg)/D$}]
if {[llength $pulse_sync_first_pins]} {
    set_false_path -to $pulse_sync_first_pins
}

# The FIFO Gray-pointer synchronizers are instantiated below TX/RX FIFO
# wrappers. Their first stages are CDC endpoints and must not be timed from
# the opposite clock domain.
set fifo_sync_first_pins [get_pins -quiet -hier -regexp {.*(wr_ptr_sync|rd_ptr_sync)/(S1|S1_reg)/D$}]
if {[llength $fifo_sync_first_pins]} {
    set_false_path -to $fifo_sync_first_pins
}

# Fail loudly in the implementation log when this XDC was attached at the
# wrong hierarchy or a naming change made the CDC selectors empty.
if {[llength [get_pins -quiet -hier -regexp {.*(wr_ptr_sync|rd_ptr_sync)/(S1|S1_reg)/D$}]] == 0} {
    puts "WARNING: can_top.xdc matched no FIFO Gray-pointer synchronizer pins"
}

# Keep the generated clock relationship intact. Do not use
# set_clock_groups -asynchronous between can_apb_clk and can_engine_clk when
# can_clk is generated by the 100 MHz Clocking Wizard input.